import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { organization } from "./auth.js";

/**
 * Workspace-scoped API keys (CONT-03/EVNT-01, D-21/D-22/D-23) -- the
 * platform's first non-session credential. `id` is the non-secret indexed
 * lookup prefix generated by `generateApiKey()` (apps/api/src/modules/
 * api-keys/api-key-auth.ts); only `secret_hash` (SHA-256) + `key_mask`
 * (prefix + last 4) are ever persisted -- the full secret crosses the wire
 * exactly once, at creation (D-22). `scopes` is reserved for v2 and unused
 * in v1: every valid key currently grants full Event/Contacts API access
 * (D-23).
 */
export const workspaceApiKeys = pgTable("workspace_api_keys", {
  id: text("id").primaryKey(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  secretHash: text("secret_hash").notNull(),
  keyMask: text("key_mask").notNull(),
  scopes: text("scopes").array().notNull().default([]),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  revokedAt: timestamp("revoked_at"),
});
